# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  #
  # if you are under proxy, run "vagrant plugin install vagrant-proxyconf"
  # and uncomment the lines below.
  #
  #if Vagrant.has_plugin?("vagrant-proxyconf")
  #  config.proxy.http = "http://xxx.xxx.xxx.xxx:xxxx/"
  #  config.proxy.https = "http://xxx.xxx.xxx.xxx:xxxx/"
  #  config.proxy.no_proxy = "localhost,127.0.0.1,192.168."
  #end

  config.vm.box = "ubuntu/trusty64"
  config.vm.network "forwarded_port", guest: 8088, host: 8088
  config.vm.network "private_network", ip: "192.168.33.10"
   config.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
   end
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y curl ruby-dev g++ git 
    sudo gem install em-websocket
    sudo gem install websocket-client-simple
    sudo apt-get install -y python-pip
    sudo pip install ws4py
    sudo apt-get install -y golang
    cd /home/vagrant; git clone https://github.com/nakasonogithub/othello.git
  SHELL
end
